### PR TITLE
feat: add story indexer to support storyStoreV7

### LINKED ISSUE #30: Add vue story indexer to support storyStoryv7
Similar to https://github.com/storybookjs/addon-svelte-csf/blob/ad8c44f6c7c64c1ab83be63f038456e0a5b6c30f/src/preset/index.js#L53-L61.

To test: remove `storyStoreV7: false,` in vite example

### PR DESCRIPTION
**Pull request by tobiasdiez**
Fixes #30.

### CODE REVIEW

**Comment by JReinhold** [comment]
As for the ID, I'm not sure `/` is allowed in story IDs. I don't think this is Chromatic crashing, but rather the built output, so if you build your Storybook locally and serve it with `npx http-serve storybook-static` then I would expect it to fail there too.

I think the `toId` function from [`@storybook/csf`](https://github.com/ComponentDriven/csf) can help you here though, as it mainly sanitizes the string to be CSF compliant. See how `addon-svelte-csf` uses it here:
https://github.com/storybookjs/addon-svelte-csf/blob/next/src/parser/extract-stories.ts#L128

As with `addon-svelte-csf` you might also need to do some collision detection. When you're sanitizing IDs and similar stuff there's a risk that you'll generate the same ID for multiple stories.

And finally I'm not sure it's a good idea to use the full file path to generate the IDs for multiple reasons:

1. It creates very long IDs, which are noticeable in the URL
2. It creates non-deterministic IDs. The same Storybook on your machine would get different IDs than on my machine, so we eg. wouldn't be able to send links to stories to each other.
3. In theory it leaks info about the host machine to everyone, eg. I can now see that the Storybook was built in `/home/runner/work/storybook-vue-addon/`. But meh? 🤷

You might get away with just using the filename instead (higher risk of collisions), or a path relative to the project root (I'm unsure how you would generate that though).
`addon-svelte-csf` generates them directly from the story names, which is not bulletproof either though.

I believe Storybook core combines the meta title with the story name for an ID, which might be the safest option.

**Comment by tobiasdiez** [comment]
Thanks for the input. I've now went with the meta tile + story name combination, and this seems to work well. Only problem is: how do I get the automatically generated meta title if no explicit one is specified? If I understand the code correctly, then the svelte indexer falls back to the story id/name in this case, but this seems prone to run into problems (imagine having to story files exporting a story with the name and no meta title).

It feels like this area would generally profit from a bit of restructuring and putting more responsibility onto the story index generator in the upstream storybook repo. I would say the language-specific story indexer should only care about extracting the id as specified (in whatever form) by the user, and maybe adding sensible fallsbacks (like the name). Then combining these file specific ids to globally unique ones, and adding prefixes like the story meta title should happen in a consistent way an abstraction level higher. This would also make it possible to prevent id conflicts across different story file formats.

**Comment by JReinhold** [comment]
> Thanks for the input. I've now went with the meta tile + story name combination, and this seems to work well. Only problem is: how do I get the automatically generated meta title if no explicit one is specified?

Sounds like you're referring to the built-in autotitle feature. It's a bit hairy to reproduce, and you'd need the `stories` globs to do that. Essentially it builds a project-relative path based on those globs, and then sanitizes that path. My suggestion would be to approximate it by autogenerate the title from the file name, and if the file name is something like `index.stories.vue`, get it from the directory name instead (native autotitle does that).

> It feels like this area would generally profit from a bit of restructuring and putting more responsibility onto the story index generator in the upstream storybook repo. I would say the language-specific story indexer should only care about extracting the id as specified (in whatever form) by the user, and maybe adding sensible fallsbacks (like the name). Then combining these file specific ids to globally unique ones, and adding prefixes like the story meta title should happen in a consistent way an abstraction level higher. This would also make it possible to prevent id conflicts across different story file formats.

I think you're right in most of this. This external indexers support is very much conceptually a v0.1 and could use a lot of API changes like these for an eventual v1 at some point. This is good feedback.

**Comment by tobiasdiez** [comment]
Since replicating the auto-name feature seems a bit overkill at the moment, I'll merge this now as it is and wait for further improvements of the upstream api!

Thanks for your help!

**Pull request merged**
